services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - prod-backend

  redisserver:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - prod-backend

  backend1:
    image: makwanagautam/prod-backend:latest
    container_name: backend1
    environment:
      - PORT=5513
    # expose:
    #   - "5513"
    ports:
    - "5513:5513"
    networks:
      - prod-backend
    depends_on:
      - mongoserver
      - redisserver
    env_file: .env

  backend2:
    image: makwanagautam/prod-backend:latest
    container_name: backend2
    environment:
      - PORT=5514
    # expose:
    #   - "5514"
    ports:
    - "5514:5514"
    networks:
      - prod-backend
    depends_on:
      - mongoserver
      - redisserver
    env_file: .env

  backend3:
    image: makwanagautam/prod-backend:latest
    container_name: backend3
    environment:
      - PORT=5515
    # expose:
    #   - "5515"
    ports:
    - "5515:5515"
    networks:
      - prod-backend
    depends_on:
      - mongoserver
      - redisserver
    env_file: .env

networks:
  prod-backend:
    driver: bridge
