services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - prod-backend

  redisserver:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - prod-backend

  backendapi:
    image: makwanagautam/prod-backend:v4
    container_name: prod-backend-server
    ports:
      - "5513:5513"
    env_file: .env
    depends_on:
      - mongoserver
      - redisserver
    networks:
      - prod-backend

networks:
  prod-backend:
    driver: bridge
